name: Basic Checks

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./frontend
      run: npm ci
    
    - name: Run security audit
      working-directory: ./frontend
      run: npm audit
    
    - name: Run linting
      working-directory: ./frontend
      run: npm run lint
    
    - name: Check file changes
      run: |
        echo "Files changed in this PR:"
        git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }}
        
    - name: Repository Status
      run: |
        echo "Branch: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}" 