name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run black
      run: black . --check --exclude="migrations/|venv/|.venv/"
      
    - name: Run isort
      run: isort . --check-only --skip migrations --skip venv --skip .venv
      
    - name: Run mypy
      run: mypy app --ignore-missing-imports
      
    - name: Run Bandit
      run: bandit -r app/ -ll -ii -x tests/

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: autoscheduler_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create test env file
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/autoscheduler_test" > .env.test
        echo "REDIS_HOST=localhost" >> .env.test
        echo "REDIS_PORT=6379" >> .env.test
        echo "TESTING=true" >> .env.test
        echo "SECRET_KEY=test_secret_key" >> .env.test
        echo "JWT_SECRET_KEY=test_jwt_secret" >> .env.test
        
    - name: Run tests
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/autoscheduler_test
        REDIS_HOST: localhost
        REDIS_PORT: 6379
        TESTING: true
        SECRET_KEY: test_secret_key
        JWT_SECRET_KEY: test_jwt_secret
      run: |
        pytest --cov=app --cov-report=xml --cov-fail-under=80
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  docker:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: docker build -t autoscheduler -f config/Dockerfile .
      
    - name: Create test env file for Docker
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@postgres:5432/autoscheduler_test" > .env.test
        echo "REDIS_HOST=redis" >> .env.test
        echo "REDIS_PORT=6379" >> .env.test
        echo "TESTING=true" >> .env.test
        echo "SECRET_KEY=test_secret_key" >> .env.test
        echo "JWT_SECRET_KEY=test_jwt_secret" >> .env.test
      
    - name: Run tests in Docker
      run: |
        docker network create test-network
        docker run --network test-network --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=autoscheduler_test -d postgres:15
        docker run --network test-network --name redis -d redis:7
        docker run --network test-network --env-file .env.test autoscheduler pytest 